# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: thheller/cljs-dev:latest
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - m2-deps-{{ checksum "project.clj" }}
          - m2-deps-

      - run: sh build-deps.sh

      - save_cache:
          paths:
            - ~/.m2
          key: m2-deps-{{ checksum "project.clj" }}

      - run: lein do test, install

      - run: sh build-cli.sh

      - run: sh build-launcher.sh

      - run: cd test-project; sh ci-run.sh

