# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: thheller/cljs-dev:latest
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  deps:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

  test:
    <<: *defaults
    steps:
      # run tests!
      - run: lein test

workflows:
  version: 2
  everything:
    jobs:
      - deps
      - test:
          requires:
            - deps
