# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: thheller/cljs-dev:latest
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - m2-deps-{{ checksum "project.clj" }}
          - m2-deps-

      - run: lein with-profile +cljs deps

      - save_cache:
          paths:
            - ~/.m2
          key: m2-deps-{{ checksum "project.clj" }}

      - run: lein test

      - run: npm init -y

      - restore_cache:
          keys:
          - npm-deps-{{ checksum "package.json" }}
          - npm-deps-

      - run: npm install ./packages/shadow-cljs

      - save_cache:
          paths:
            - ~/repo/node_modules
          key: npm-deps-{{ checksum "package.json" }}

      - run: lein run -m shadow.cljs.devtools.cli release cli

      - run: npx shadow-cljs --cli-info

      - run: npx shadow-cljs start

      - run: npx shadow-cljs clj-run demo.runnable/foo

      - run: npx shadow-cljs compile browser test-node

      - run: npx shadow-cljs stop

      - run: node out/demo-test-node/script.js

